using UnityEngine;
using System.Collections;

public class FollowCamera : MonoBehaviour {

	[SerializeField]// create a field in main camera options ...
	private Transform player;// to transform the location of camera as the player moves ...
	[SerializeField]// create a field in main camera options ...
	private Vector3 offset;// to fix the position of the camera behind the player ...
	private float cameraFollowSpeed = 5f;// to rotate the camera as the player moves left or right ...
	
	// Update is called once per frame
	void Update () {

		//add both the vectors so when the camera rotates camera will do not change the distance from player ...
		Vector3 newPosition = player.position + offset;

		// slow the camera when the frogs rotares ...
		transform.position = Vector3.Lerp (transform.position, newPosition, cameraFollowSpeed * Time.deltaTime);
		//transform.position = current position of value ...
		//newPosition = new position of player that is being updated for every second ... 
		//cameraFollowSpeed * Time.deltaTime = is the rotating time of the camera ...
	}
}
